### ISSUE TITLE
Error while trying to post

### ISSUE THREAD

**Issue by tiagonbotelho** [CozyCo/slack-post#10]
I'm trying to post something to a channel but it gives me this error:

/Users/tiagobotelho/.rvm/gems/ruby-2.1.5/gems/slack-post-0.2.1/lib/slack/post.rb:45:in `post_with_attachments': There was an error while trying to post. Error was: No hooks (RuntimeError)
	from /Users/tiagobotelho/.rvm/gems/ruby-2.1.5/gems/slack-post-0.2.1/lib/slack/post.rb:58:in `post'
	from init.rb:10:in `<main>'

I can post my code too if it helps

**Comment by mgreensmith** [comment]
This is a configuration issue - Slack is saying that you do not have a webhook configured on their side. So either your configuration is incorrect, or your webhook is not enabled on the Slack side. You can find more information at https://api.slack.com/incoming-webhooks
